[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "dist"

# Redirect all API calls to Netlify Functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api"
  status = 200

# Redirect all other routes to index.html for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Node.js version
[build.environment]
  NODE_VERSION = "18"
