[build]
  command = "npm install && ./node_modules/.bin/vite build"
  functions = "netlify/functions"
  publish = "dist"

# Headers for CORS
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, Authorization, Accept-Language, X-Preferred-Language"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Credentials = "true"

# Headers for function endpoints
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, Authorization, Accept-Language, X-Preferred-Language"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Credentials = "true"

# Redirect all API calls to Netlify Functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api"
  status = 200
  force = true

# Redirect all other routes to index.html for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev"
  port = 5173
  publish = "dist"

# Node.js version for Netlify
[build.environment]
  NODE_VERSION = "18"
  NODE_ENV = "development"

# Environment variables for production
[context.production.environment]
  NODE_ENV = "production"
  VITE_API_BASE_URL = "https://ayat-sains-insight.netlify.app"
